spring:
  datasource:
    url: jdbc:mysql://10.206.0.10:3306/database_test
    username: root
    password: zr&zy19950310
    driver-class-name: com.mysql.jdbc.Driver
#    type: com.zaxxer.hikari.HikariDataSource
